### PR TITLE
Multiple APKs support added

### PR DESCRIPTION
**Pull request by koral--**
Feature mainly useful with split APKs.
If the new input `is_use_apk_path_list` is set `true` then `apk_path_list` (by default equal `${BITRISE_APK_PATH_LIST}`) is taken into account instead of `apk_path`.

Instead of adding a bunch of the same steps differing only by APK path (and hardcoding each of those paths), you can use one step without additional configuration.

### CODE REVIEW

**Comment by doomsayer13** [comment]
Thanks for the PR.

**Comment by godrei** [comment]
Hi @koral,
thanks for the pr!

May i ask your why did you wire in the `is_use_apk_path_list` input? Would not it be better to use `apk_path_list` input's value if defined, otherwise the `apk_path` input's value?

There is a typo in output env var's key: `HOCKEYAPP_DEPLOY_PUBLIC_URL:_LIST` (`:`).

**Comment by koral--** [comment]
I've just fixed the typo.
I've added `is_use_apk_path_list` because default value of `apk_path_list` (`$BITRISE_APK_PATH_LIST`) is always exported by Gradle runner step.
So without additional switch, behavior may change for existing users if they update step version or they use `always latest` version.

**Comment by koral--** [comment]
Is there anything more to change?

**Comment by viktorbenei** [comment]
> I've added is_use_apk_path_list because default value of apk_path_list ($BITRISE_APK_PATH_LIST) is always exported by Gradle runner step.

@koral-- you're right but that list should always be correct as well, I mean if there's only one APK it should only include a single one, otherwise more than one.

IMO we should NOT add any additional inputs. Simply leave `apk_path` as it is, or change it to `$BITRISE_APK_PATH_LIST`, and the step internally should be able to handle if that's just a single APK or if it's more than one.

This way the step by default could work as before, and if you need multi APK then you simply specify `$BITRISE_APK_PATH_LIST` as the value.

@koral-- @godrei WDYT?

**Comment by koral--** [comment]
I considered the following case: in existing app, Gradle Runner step builds 2 APKs (let's say they are split by ABI, there is one for armeabi-v7a and second for arm64-v8a), then Hockey App upload step uploads only the latest APK.

If HA step uses `always latest` version and we change behavior like you said, two APKs will be uploaded to HA instead of one.

For example if arm64-v8a is the first one, testers will receive notification about that, if someone has armeabi-v7a device, she will be unable to install that version.

**Comment by viktorbenei** [comment]
> If HA step uses always latest version and we change behavior like you said, two APKs will be uploaded to HA instead of one.

That's why I would keep the default value to be `$BITRISE_APK_PATH`, and if someone needs the multi apk mode s/he can set `$BITRISE_APK_PATH_LIST` instead (for the `apk_path` input).

**Comment by koral--** [comment]
So to sum up:
* there should be only one additional input `apk_path_list` with no default value
* `apk_path` should become not required
* if someone want to upload multiple APKs, she has to assign a value (perhaps `$BITRISE_APK_PATH_LIST`)
* if `apk_path_list` is provided then `apk_path` is ignored (a warning may be printed if it is not in `apk_path_list`)
Right?

**Comment by viktorbenei** [comment]
No, personally I'd go with no additional input. Zero.

Simply, the `apk_path` input should be able to handle both cases (if a single APK is provided, as well as if more than one is provided). 

This way the user could simply change the value of `apk_path` as s/he want to. Specifying a single apk (default, with `$BITRISE_APK_PATH`), specifying multiple APKs either manually by listing them like `/path/1 | /path/2` or via an env var like `$BITRISE_APK_PATH_LIST`.

This would be 100% compatible with previous versions and if someone wants to specify multiple APKs then s/he have to change a config anyway, i think that config should be the **value** of the `apk_path` input.

Of course the `apk_path` input's description should be updated to include this (that it supports `|` style multi value), but this way there would be no additional input at all.

**Comment by koral--** [comment]
OK, I'll update PR according to that.

**Comment by viktorbenei** [comment]
Thanks - but feel free to disagree @koral-- ! It's just my "IMO" ;)

**Comment by viktorbenei** [comment]
That said I do think that this would be probably the best way to do this, as it's 100% compatible and really flexible.

On the otherhand a bit more complex to setup (compared to a toggle).

**Comment by koral--** [comment]
It seems that there is already a PR with exactly that change made by bitrise staff: https://github.com/bitrise-steplib/steps-hockeyapp-android-deploy/pull/11. As far I can see only tests and `apk_path` input description are missing there.
Should I create a new PR based on #11 with those additions or just wait until they finish everything?

BTW 
> it's 100% compatible

Theoretically it is not 100%. As we discussed several months ago: https://discuss.bitrise.io/t/arrays-in-step-outputs/2200/5 it will stop working if someone has a `|` in APK path. But I believe such regression can be ignored.

**Comment by viktorbenei** [comment]
To be honest I didn't know we started to work on this - good catch @koral-- ! :)

It's been on our list for quite some time, it seems it finally was added to last week's sprint, thanks to our recent hire ( @kdobmayer ) we could progress with our backlog. It should have been started way earlier, but there was always something a bit more important..

Anyway, @koral-- I'd say it's up to you; if you're OK with that direction then I'd say yes, leave it to @kdobmayer to finish it, but if you're not OK / have any feedback just let us know! And of course sorry for the inconvenience & confusion.

**Comment by koral--** [comment]
OK, I'll close this PR and wait for #11 to be finished. Until that I can use my fork via `git::` source.

**Comment by viktorbenei** [comment]
Sure, `git::` of course works, thanks for understanding and sorry for the inconvenience.

**Pull request closed without merging**
